import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'zh' | 'en';

// 所有翻译文本
const translations = {
  zh: {
    // 通用
    'common.loading': '加载中...',
    'common.noData': '暂无数据',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.submit': '提交',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',
    'common.back': '返回',
    'common.viewMore': '查看更多',
    'common.all': '全部',
    'common.refresh': '刷新',
    'common.search': '搜索',
    'common.noAI': '无 AI',

    // 导航
    'nav.discover': '发现',
    'nav.artists': '画师',
    'nav.gallery': '广场',
    'nav.community': '社区',
    'nav.messages': '消息',
    'nav.admin': '管理',
    'nav.profile': '个人主页',
    'nav.logout': '退出登录',
    'nav.login': '登录 / 注册',
    'nav.verified': '已认证',
    'nav.pending': '审核中',
    'nav.verify': '画师认证',
    'nav.switchTheme': '切换主题',

    // 首页
    'home.hero.badge': '🚫 无 AI 生成 · 纯原创创作平台',
    'home.hero.title1': '找到你心中',
    'home.hero.title2': '最完美的画师',
    'home.hero.subtitle': '纯画 · 专注原创，每一笔都有温度。连接最优秀的手绘/板绘画师，让你的想象变成现实。',
    'home.hero.explore': '探索画师',
    'home.hero.gallery': '浏览广场',
    'home.hero.stats.artists': '认证画师',
    'home.hero.stats.commissions': '完成约稿',
    'home.hero.stats.satisfaction': '满意度',
    'home.rules.title': '平台核心原则',
    'home.rules.subtitle': '我们相信原创的力量，每一条规则都是对创作者的承诺',
    'home.rules.minPrice.title': '¥70 起步保障',
    'home.rules.minPrice.desc': '所有约稿起价不低于 70 元，保障画师的创作价值与劳动报酬。',
    'home.rules.noAI.title': '禁止 AI 生成',
    'home.rules.noAI.desc': '平台严格禁止 AI 生成图，一经发现立即下架，账号标记警告。',
    'home.rules.certified.title': '画师认证制',
    'home.rules.certified.desc': '所有接稿画师须通过人工审核认证，确保作品真实性与质量。',
    'home.rules.escrow.title': '定金代管保障',
    'home.rules.escrow.desc': '定金由平台代管，约稿完成后结算，保障双方交易安全。',
    'home.cta.title': '准备好了吗？',
    'home.cta.subtitle': '无论你是寻找画师的约稿人，还是希望展示才华的创作者，纯画都欢迎你',
    'home.cta.join': '立即加入',
    'home.cta.learnMore': '了解更多',

    // 广场
    'gallery.empty': '暂无作品',
    'gallery.emptyDesc': '等待画师们上传精彩作品 🐾',
    'gallery.loadMore': '加载更多',
    'gallery.end': '已经到底啦，期待更多画师加入纯画 🐾',
    'gallery.digital': '板绘',
    'gallery.handdrawn': '手绘',
    'gallery.digitalDesc': '数字绘画，插画设计，游戏立绘',
    'gallery.handdrawnDesc': '水彩素描，油画国画，传统艺术',

    // 画师
    'artists.title': '发现画师',
    'artists.subtitle': '遇见每一位有温度的创作者',
    'artists.searchPlaceholder': '搜索画师名称...',
    'artists.filterAll': '全部',
    'artists.filterDigital': '板绘',
    'artists.filterHanddrawn': '手绘',
    'artists.pricingNote': '💡 平台规定：所有约稿起价不低于 ¥70，请尊重画师的创作价值',
    'artists.noResults': '没有找到匹配的画师',
    'artists.noResultsDesc': '试试其他关键词或风格筛选',
    'artists.verified': '认证画师',
    'artists.viewProfile': '查看主页',
    'artists.commission': '发起约稿',
    'artists.minPrice': '起价',

    // 登录/注册
    'auth.login': '登录',
    'auth.joinPureDraw': '加入纯画',
    'auth.welcomeBackTitle': '欢迎回来',
    'auth.loginSubtitle': '遇见指尖的温度',
    'auth.username': '用户名',
    'auth.password': '密码',
    'auth.usernamePlaceholder': '你的用户名',
    'auth.regUsernamePlaceholder': '想一个响亮的名字',
    'auth.passwordPlaceholder': '设置你的秘密口令',
    'auth.loginBtn': '立即登录',
    'auth.registerBtn': '开启艺术之旅',
    'auth.createAccount': '创建账号',
    'auth.registerSubtitle': '开启你的纯净创作之旅',
    'auth.myRole': '我的身份',
    'auth.roleClient': '约稿人',
    'auth.roleClientDesc': '寻找灵魂画笔',
    'auth.roleArtist': '画师',
    'auth.roleArtistDesc': '展示原创才华',
    'auth.agreeTerms': '注册即代表您同意我们的',
    'auth.and': '和',
    'auth.termsOfService': '服务协议',
    'auth.privacyPolicy': '隐私政策',
    'auth.fillFields': '请填写用户名和密码',
    'auth.usernameTooShort': '用户名至少 3 个字符',
    'auth.loginFailed': '登录失败',
    'auth.registerFailed': '注册失败',
    'auth.welcomeBack': '欢迎回来！',
    'auth.registerSuccess': '注册成功！',

    // 社区
    'community.title': '创作者社区',
    'community.subtitle': '分享灵感，交流创作，遇见同行',
    'community.newPost': '发布帖子',
    'community.postPlaceholder': '分享你的创作心得或灵感...',
    'community.addImage': '添加图片',
    'community.publish': '发布',
    'community.noPost': '还没有帖子',
    'community.noPostDesc': '成为第一个分享创作心得的人吧',
    'community.comment': '评论',
    'community.like': '点赞',
    'community.replyPlaceholder': '写下你的评论...',
    'community.loginRequired': '请先登录后才能访问社区',

    // 个人主页
    'profile.artworks': '作品展示',
    'profile.noArtwork': '暂无作品',
    'profile.commission': '发起约稿',
    'profile.editProfile': '编辑资料',
    'profile.verified': '认证画师',
    'profile.artist': '画师',
    'profile.pending': '审核中',
    'profile.client': '约稿人',
    'profile.digital': '板绘',
    'profile.handdrawn': '手绘',
    'profile.bio': '个人简介',
    'profile.noBio': '这个画师很懒，什么都没有写~',
    'profile.minPrice': '起价',
    'profile.joinDate': '加入时间',
    'profile.joinedAt': '加入于',
    'profile.showcase': '作品橱窗',
    'profile.about': '关于画师',
    'profile.clientTitle': '这是一位约稿人',
    'profile.clientDesc': '约稿人专注于寻找心仪的画师。如果你是画师，欢迎通过认证后展示你的作品 🐾',
    'profile.applyArtist': '申请成为画师',
    'profile.sendMessage': '发送消息',
    'profile.userNotFound': '用户未找到 🐾',
    'profile.noArtworkDesc': '画师正在努力创作中 🐾',
    'profile.speciality': '擅长领域',
    'profile.certStatus': '认证状态',
    'profile.commissionNotes': '约稿须知',
    'profile.note1': '所有作品均为纯手工创作，拒绝 AI 生成',
    'profile.note2': '约稿起价 ¥70，定金 ¥30 由平台托管',
    'profile.note3': '草图阶段可申请修改，成图后 24 小时内可发起反馈下架',
    'profile.note4': '请尊重画师创作时间，耐心等待作品完成',
    'profile.changeAvatar': '更换头像',
    'profile.digitalArt': '板绘创作',
    'profile.handdrawnArt': '手绘创作',
    'profile.certVerified': '已认证',
    'profile.certPending': '审核中',

    // 画师认证（三步骤）
    'verify.title': '画师认证',
    'verify.subtitle': '提交你的作品集，等待人工审核',
    'verify.step1.title': '选择创作类型',
    'verify.step1.desc': '请选择你的创作风格（可多选）',
    'verify.step1.handdrawn': '手绘类',
    'verify.step1.digital': '板绘类',
    'verify.step2.title': '上传作品',
    'verify.step2.desc': '请上传至少 3 张原创作品，展示你的绘画风格',
    'verify.step2.minHint': '至少上传 3 张作品',
    'verify.step3.title': '感谢您选择成为画师',
    'verify.step3.subtitle': '这一定是一个勇敢的决定',
    'verify.step3.desc': '我们已收到您的认证申请，请耐心等待人工审核。审核通过后，您的作品将出现在广场和个人主页 🐾',
    'verify.step3.backHome': '回到首页',
    'verify.next': '下一步',
    'verify.prev': '上一步',
    'verify.submit': '提交认证申请',
    'verify.uploadTitle': '上传作品',
    'verify.uploadDesc': '请上传至少 3 张原创作品（最多 9 张），展示你的绘画风格',
    'verify.artworkType': '作品类型',
    'verify.digital': '板绘',
    'verify.handdrawn': '手绘',
    'verify.submitBtn': '提交认证',
    'verify.pendingTitle': '审核中',
    'verify.pendingDesc': '你的认证申请正在审核中，请耐心等待 🐾',
    'verify.pendingBackHome': '回到首页',
    'verify.verifiedTitle': '认证成功',
    'verify.verifiedDesc': '您已通过认证，现在可以开始接稿啦！',
    'verify.verifiedGoProfile': '前往个人主页',
    'verify.rejectedTitle': '未通过',
    'verify.rejectedDesc': '你的认证未通过，请根据反馈重新提交',
    'verify.resubmit': '重新提交',
    'verify.selectAtLeastOne': '请至少选择一个创作类型标签',
    'verify.uploadAtLeastThree': '请至少上传 3 张作品',
    'verify.submitSuccess': '申请已提交，请等待管理员审核',
    'verify.submitFailed': '提交失败',

    // 消息
    'messages.title': '消息',
    'messages.subtitle': '沟通指尖的温度 🐾',
    'messages.escrow': '全程担保交易',
    'messages.noMessages': '暂无消息',
    'messages.noMessagesDesc': '开始一段约稿对话吧',
    'messages.findArtists': '发现画师',
    'messages.artist': '画师',
    'messages.client': '约稿人',
    'messages.noAI': '无 AI',
    'messages.noAIDesc': '100% 人工审核',
    'messages.depositBadge': '定金保',
    'messages.depositBadgeDesc': '平台全程托管',
    'messages.fastReply': '极速应',
    'messages.fastReplyDesc': '画师快速反馈',
    'messages.aiWelcomePreview': '感谢你使用纯画 🐾',
    'messages.aiSubtitle': '纯画官方助手',
    'messages.aiReadOnly': '官方助手不支持回复，如需帮助请联系平台',
    'messages.selectConversation': '选择一个对话',
    'messages.selectConversationDesc': '从左侧选择联系人开始聊天',
    'messages.activeCommission': '当前约稿',
    'messages.acceptCommission': '接受约稿',
    'messages.payDeposit': '支付定金',
    'messages.viewDetail': '查看详情',
    'messages.sendFailed': '消息发送失败',
    'messages.commissionSent': '约稿需求已发送',
    'messages.commissionFailed': '发起约稿失败',
    'messages.commissionAccepted': '已接受约稿',
    'messages.priceMin': '价格不得低于 70 元',

    // 聊天
    'chat.inputPlaceholder': '输入消息...',
    'chat.send': '发送',
    'chat.commission': '约稿详情',

    // 约稿详情
    'commission.title': '约稿详情',
    'commission.description': '需求描述',
    'commission.price': '价格',
    'commission.deposit': '定金',
    'commission.status': '状态',
    'commission.sketchDeadline': '草图截止',
    'commission.finalDeadline': '成图截止',
    'commission.uploadSketch': '上传草图',
    'commission.uploadFinal': '上传成图',
    'commission.confirmReceipt': '确认收货',
    'commission.payDeposit': '支付定金',
    'commission.payFinal': '支付尾款',
    'commission.report': '反馈下架',
    'commission.statusMap.pending_agreement': '等待协商',
    'commission.statusMap.agreed': '已协商',
    'commission.statusMap.deposit_paid': '定金已付',
    'commission.statusMap.sketch_uploaded': '草图已上传',
    'commission.statusMap.final_uploaded': '成图已上传',
    'commission.statusMap.completed': '已完成',
    'commission.statusMap.reported': '已申请下架',
    'commission.statusMap.refunded': '已退款',
    'commission.statusMap.in_progress': '进行中',
    'commission.orderId': '订单号',
    'commission.notFound': '约稿未找到 🐾',
    'commission.backToMessages': '返回消息',
    'commission.deliveryArea': '作品交付区',
    'commission.sketchSection': '草图环节',
    'commission.finalSection': '成图环节',
    'commission.noSketch': '暂无草图',
    'commission.noFinal': '暂无成图',
    'commission.confirmSketch': '确认草图',
    'commission.requestRevision': '申请修改',
    'commission.confirmAndPay': '确认收货并付尾款',
    'commission.depositTitle': '协商达成，请支付定金',
    'commission.depositDesc': '支付定金后画师将开始创作。定金由平台托管，确保双方权益 🐾',
    'commission.payDepositBtn': '支付定金 ¥30',
    'commission.counterpart': '约稿对象',
    'commission.sendMessage': '发送消息',
    'commission.clientLabel': '约稿人',
    'commission.artistLabel': '画师',
    'commission.afterSale': '售后保障',
    'commission.afterSale1': '画师交付草图前，您可以随时终止约稿，定金不予退还。',
    'commission.afterSale2': '草图阶段若不满意，可申请重画或终止约稿并退回 ¥25 定金。',
    'commission.afterSale3': '收到成图后若发现 AI 生成迹象，24 小时内可发起反馈下架，核实后退款 80%。',
    'commission.terminateBtn': '终止约稿并退 25 元',
    'commission.reportAI': '反馈下架',
    'commission.reportPending': '反馈下架功能开发中，请在收到图后24h内联系客服',
    'commission.totalLabel': '约稿总额',
    'commission.deadlineLabel': '截止时间',
    'commission.revisionTip': '请通过对话框与画师沟通修改需求',
    'commission.payModal.deposit': '支付定金',
    'commission.payModal.balance': '支付尾款',
    'commission.payModal.scanTip': '请使用微信扫码支付',
    'commission.payModal.wechat': '微信支付加密协议',
    'commission.payModal.testBtn': '模拟支付成功 (测试用)',
    'commission.payModal.scanOpened': '支付通道已建立，请扫码支付 🐾',
    'commission.toast.depositPaid': '定金支付成功，订单已开启！',
    'commission.toast.finalPaid': '尾款支付成功，交易已完成！',
    'commission.toast.paymentMsg': '[系统消息] 我已完成支付，请查收。',
    'commission.toast.sketchUploaded': '草图已上传！',
    'commission.toast.finalUploaded': '成图已上传，请等待约稿人确认。',
    'commission.toast.uploadFailed': '保存失败',
    'commission.toast.sketchConfirmed': '草图已确认，请画师继续完成成图！',
    'commission.toast.refunded': '已为您退回 25 元定金，欢迎寻找下一位心仪画师 🐾',
    'commission.toast.sketchMsg': '[系统消息] 我已上传了草图，请前往详情页查看。',
    'commission.toast.finalMsg': '[系统消息] 我已上传了成图，请前往详情页查看。',
    'commission.toast.acceptMsg': '[系统消息] 我已接受您的约稿需求，请支付定金。',
    'chat.sayHi': '打个招呼吧，开启一段纯净的艺术交流 🐾',
    'chat.systemMsgPrefix': '[系统消息]',
    'chat.commissionRequest': '发起约稿需求',
    'chat.reqLabel': '需求描述',
    'chat.reqPlaceholder': '请详细描述您的约稿需求，如风格、构图、用途等...',
    'chat.priceLabel': '约稿价格 (起价 ¥70)',
    'chat.depositFixed': '定金 (固定)',
    'chat.depositFixedValue': '¥30',
    'chat.sketchDeadline': '草图截止时间',
    'chat.finalDeadline': '成图截止时间',
    'chat.sendReq': '发送需求',
    'chat.commSentMsg': '发起约稿需求，请查收。需求描述',
    'chat.statusNegotiating': '协商需求中',
    'chat.statusAgreed': '待付定金',
    'chat.statusSketching': '制作草图中',
    'chat.statusSketchReview': '草图确认中',
    'chat.statusFinalizing': '制作成图中',
    'chat.statusCompleted': '已完成',
    'chat.statusDisputed': '反馈下架审核中',
    'chat.statusRefunded': '已退款',
    'chat.artistRoleLabel': '认证画师',
    'chat.clientRoleLabel': '约稿人',
    'chat.currentComm': '当前约稿',
    'chat.commProgress': '约稿进度',
    'chat.totalPrice': '总价',
    'chat.depositLabel': '定金',
    'chat.deadlineLabel': '截止时间',
    'chat.acceptBtn': '接受并启动约稿',
    'chat.payDepositBtn': '支付定金 (¥30)',
    'chat.viewDetail': '查看完整详情',
    'chat.platformGuarantee': '约稿由纯画平台全程担保 🐾',
    'chat.msgSendFailed': '消息发送失败',
    'chat.priceTooLow': '价格不得低于 70 元',
    'chat.reqSent': '约稿需求已发送',
    'chat.reqFailed': '发起约稿失败',
    'chat.accepted': '已接受约稿',
    'chat.opFailed': '操作失败',
    'community.fillForm': '请填写标题和内容',
    'profile.admin': '管理员',
    'profile.bioDefault': '每一笔都是心意，每一画都是温度 🐾',
    'verify.artworkTitleBase': '认证作品',
    'verify.selectedTags': '已选：',
    'verify.uploadedReady': '张，可以提交了',
    'notFound.title': '页面未找到',
    'notFound.error': '错误',
    'notFound.desc': '页面可能已被删除或不存在，请检查网址是否正确。',
    'notFound.backHome': '返回首页',
    'imageUpload.label': '上传图片',
    'imageUpload.unsupported': '不支持的文件格式，请上传图片文件',
    'imageUpload.compressing': '文件超过 1MB，正在自动压缩中...',
    'imageUpload.inProgress': '正在压缩图片...',
    'imageUpload.compressed': '压缩完成，最终大小',
    'imageUpload.compressedToast': '图片已自动压缩至',
    'imageUpload.success': '图片上传成功！',
    'imageUpload.failed': '上传失败',
    'imageUpload.hint': '支持 JPG, PNG, WEBP (最大 1MB)',
    'imageUpload.uploading': '正在上传...',
    'imageUpload.confirm': '确认上传',
    'admin.keywords.tab': '关键词回复',
    'admin.keywords.title': '蜗牛猫关键词回复管理',
    'admin.keywords.desc': '优先级越高的关键词越先被匹配。消息中含多个关键词时，返回优先级最高的回复。',
    'admin.keywords.add': '新增关键词',
    'admin.keywords.empty': '暂无关键词',
    'admin.keywords.emptyDesc': '点击"新增关键词"添加第一条回复规则',
    'admin.keywords.editTitle': '编辑关键词回复',
    'admin.keywords.addTitle': '新增关键词回复',
    'admin.keywords.keywordLabel': '关键词（用户消息包含此词即触发）',
    'admin.keywords.keywordPlaceholder': '例如：认证、价格、退款...',
    'admin.keywords.replyLabel': '自动回复内容',
    'admin.keywords.replyPlaceholder': '输入蜗牛猫小助手的回复内容...',
    'admin.keywords.priorityLabel': '优先级（数字越大越优先匹配）',
    'admin.keywords.cancel': '取消',
    'admin.keywords.save': '保存',
    'admin.keywords.deleteTitle': '确认删除',
    'admin.keywords.deleteDesc': '删除后该关键词将不再触发自动回复，确认继续？',
    'admin.keywords.confirmDelete': '确认删除',
    'admin.keywords.updated': '关键词已更新',
    'admin.keywords.added': '关键词已添加',
    'admin.keywords.saveFailed': '保存失败',
    'admin.keywords.deleted': '已删除',
    'admin.keywords.deleteFailed': '删除失败',
    'admin.keywords.emptyCheck': '关键词和回复内容不能为空',
    'admin.keywords.showQuick': '展示为快捷问题',
    'admin.keywords.showQuickTip': '开启后该关键词会作为快捷问题出现在小助手对话框中',
    'quickQ.title': '常见问题',
    'quickQ.hint': '点击快速提问',
    'home.featuredArtists': '推荐画师',
    'home.featuredDesc': '遇见让你心动的灵魂画笔',
    'home.noBio': '该画师比较懒...',
    'home.noArtists': '暂时没有画师，快去成为第一位认证画师吧！🐾',

    // 管理后台
    'admin.title': '管理后台',
    'admin.subtitle': '维护纯净的原创绘画交流环境 🐾',
    'admin.verifications': '认证审核',
    'admin.reports': '反馈下架处理',
    'admin.users': '用户管理',
    'admin.approve': '通过',
    'admin.approveBtn': '通过',
    'admin.reject': '拒绝',
    'admin.rejectBtn': '驳回',
    'admin.rejectReason': '拒绝原因',
    'admin.rejectPrompt': '请输入驳回原因：',
    'admin.noVerifications': '暂时没有待审核的申请 🐾',
    'admin.noReports': '没有待处理的反馈下架',
    'admin.noReportsDesc': '目前环境非常纯净，所有小猫都在愉快地画画 🐾',
    'admin.pending': '待审核',
    'admin.approved': '已通过',
    'admin.rejected': '已拒绝',
    'admin.approveSuccess': '画师已通过认证',
    'admin.rejectSuccess': '申请已驳回',
    'admin.actionFailed': '操作失败',
    'admin.artistBio': '画师简介',
    'admin.defaultBio': '该画师比较懒，没有填写个人简介...',
    'admin.styleDigital': '板绘',
    'admin.styleHanddrawn': '手绘',
    'admin.verificationTab': '认证审核',
    'admin.reportTab': '反馈下架',

    // 社区
    'community.original': '原创内容',
    'community.titlePlaceholder': '标题 (给你的灵感取个名字)',
    'community.maxImages': '最多 4 张',
    'community.uploadImage': '上传图片',
    'community.likedMsg': '已点赞 🐾',
    'community.commentSoon': '评论功能开发中',
    'community.shareSuccess': '分享成功',
    'community.publishSuccess': '发布成功！',
    'community.publishFailed': '发布失败: ',
    'community.loginToPost': '请先登录后才能发帖',
  },
  en: {
    // 通用
    'common.loading': 'Loading...',
    'common.noData': 'No data',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.submit': 'Submit',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.viewMore': 'View More',
    'common.all': 'All',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.noAI': 'No AI',

    // 导航
    'nav.discover': 'Discover',
    'nav.artists': 'Artists',
    'nav.gallery': 'Gallery',
    'nav.community': 'Community',
    'nav.messages': 'Messages',
    'nav.admin': 'Admin',
    'nav.profile': 'My Profile',
    'nav.logout': 'Log Out',
    'nav.login': 'Login / Sign Up',
    'nav.verified': 'Verified',
    'nav.pending': 'Under Review',
    'nav.verify': 'Get Certified',
    'nav.switchTheme': 'Switch Theme',

    // 首页
    'home.hero.badge': '🚫 No AI Generated · Pure Original Art Platform',
    'home.hero.title1': 'Find Your',
    'home.hero.title2': 'Perfect Artist',
    'home.hero.subtitle': 'PureDraw · Dedicated to original art, every stroke has soul. Connect with the best illustrators and bring your imagination to life.',
    'home.hero.explore': 'Explore Artists',
    'home.hero.gallery': 'Browse Gallery',
    'home.hero.stats.artists': 'Certified Artists',
    'home.hero.stats.commissions': 'Commissions Done',
    'home.hero.stats.satisfaction': 'Satisfaction',
    'home.rules.title': 'Platform Principles',
    'home.rules.subtitle': 'We believe in the power of originality — every rule is a promise to creators',
    'home.rules.minPrice.title': '¥70 Minimum Guarantee',
    'home.rules.minPrice.desc': 'All commissions start at ¥70 minimum to ensure fair compensation for artists.',
    'home.rules.noAI.title': 'Zero AI Policy',
    'home.rules.noAI.desc': 'AI-generated content is strictly prohibited. Violations result in immediate removal and account warning.',
    'home.rules.certified.title': 'Certified Artists Only',
    'home.rules.certified.desc': 'All commission-taking artists must pass manual verification to ensure authenticity and quality.',
    'home.rules.escrow.title': 'Escrow Protection',
    'home.rules.escrow.desc': 'Deposits are held in escrow by the platform and released upon completion to protect both parties.',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.subtitle': 'Whether you are looking for an artist or want to showcase your talent, PureDraw welcomes you',
    'home.cta.join': 'Join Now',
    'home.cta.learnMore': 'Learn More',

    // 广场
    'gallery.empty': 'No Artworks Yet',
    'gallery.emptyDesc': 'Waiting for artists to upload their work 🐾',
    'gallery.loadMore': 'Load More',
    'gallery.end': 'You have reached the end. Looking forward to more artists joining PureDraw 🐾',
    'gallery.digitalDesc': 'Digital illustration, character design, game art',
    'gallery.handdrawnDesc': 'Watercolor, sketch, oil painting, traditional art',
    'gallery.digital': 'Digital',
    'gallery.handdrawn': 'Traditional',

    // 画师
    'artists.title': 'Discover Artists',
    'artists.subtitle': 'Meet every creator with a soul',
    'artists.searchPlaceholder': 'Search artists...',
    'artists.filterAll': 'All',
    'artists.filterDigital': 'Digital',
    'artists.filterHanddrawn': 'Traditional',
    'artists.pricingNote': '💡 Platform rule: All commissions start at ¥70. Please respect artists\' creative value.',
    'artists.noResults': 'No artists found',
    'artists.noResultsDesc': 'Try different keywords or style filters',
    'artists.verified': 'Certified Artist',
    'artists.viewProfile': 'View Profile',
    'artists.commission': 'Commission',
    'artists.minPrice': 'Starting at',

    // 登录/注册
    'auth.login': 'Login',
    'auth.joinPureDraw': 'Join PureDraw',
    'auth.welcomeBackTitle': 'Welcome Back',
    'auth.loginSubtitle': 'Feel the warmth of every stroke',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.usernamePlaceholder': 'Your username',
    'auth.regUsernamePlaceholder': 'Pick a cool name',
    'auth.passwordPlaceholder': 'Set your password',
    'auth.loginBtn': 'Login',
    'auth.registerBtn': 'Start Your Journey',
    'auth.createAccount': 'Create Account',
    'auth.registerSubtitle': 'Begin your pure creative journey',
    'auth.myRole': 'My Role',
    'auth.roleClient': 'Client',
    'auth.roleClientDesc': 'Find your artist',
    'auth.roleArtist': 'Artist',
    'auth.roleArtistDesc': 'Showcase your talent',
    'auth.agreeTerms': 'By registering, you agree to our ',
    'auth.and': ' and ',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.fillFields': 'Please fill in username and password',
    'auth.usernameTooShort': 'Username must be at least 3 characters',
    'auth.loginFailed': 'Login failed',
    'auth.registerFailed': 'Registration failed',
    'auth.welcomeBack': 'Welcome back!',
    'auth.registerSuccess': 'Registration successful!',

    // 社区
    'community.title': 'Creator Community',
    'community.subtitle': 'Share inspiration, exchange ideas, meet fellow creators',
    'community.newPost': 'New Post',
    'community.postPlaceholder': 'Share your creative experience or inspiration...',
    'community.addImage': 'Add Image',
    'community.publish': 'Publish',
    'community.noPost': 'No posts yet',
    'community.noPostDesc': 'Be the first to share your creative experience',
    'community.comment': 'Comment',
    'community.like': 'Like',
    'community.replyPlaceholder': 'Write your comment...',
    'community.loginRequired': 'Please log in to access the community',

    // 个人主页
    'profile.artworks': 'Artworks',
    'profile.noArtwork': 'No artworks yet',
    'profile.commission': 'Commission',
    'profile.editProfile': 'Edit Profile',
    'profile.verified': 'Certified Artist',
    'profile.artist': 'Artist',
    'profile.pending': 'Under Review',
    'profile.client': 'Client',
    'profile.digital': 'Digital',
    'profile.handdrawn': 'Traditional',
    'profile.bio': 'Bio',
    'profile.noBio': "This artist hasn't written anything yet~",
    'profile.minPrice': 'Starting at',
    'profile.joinDate': 'Joined',
    'profile.joinedAt': 'Joined',
    'profile.showcase': 'Showcase',
    'profile.about': 'About',
    'profile.clientTitle': 'This is a Client',
    'profile.clientDesc': 'Clients are looking for their perfect artist. If you are an artist, get certified to showcase your work 🐾',
    'profile.applyArtist': 'Apply to Become an Artist',
    'profile.sendMessage': 'Send Message',
    'profile.userNotFound': 'User not found 🐾',
    'profile.noArtworkDesc': 'The artist is working hard on new pieces 🐾',
    'profile.speciality': 'Speciality',
    'profile.certStatus': 'Certification',
    'profile.commissionNotes': 'Commission Notes',
    'profile.note1': 'All artworks are hand-crafted, no AI generation',
    'profile.note2': 'Commissions start at ¥70, ¥30 deposit held in escrow',
    'profile.note3': 'Revisions available at sketch stage; feedback-takedown within 24h of final delivery',
    'profile.note4': 'Please respect the artist\'s time and wait patiently',
    'profile.changeAvatar': 'Change Avatar',
    'profile.digitalArt': 'Digital Art',
    'profile.handdrawnArt': 'Traditional Art',
    'profile.certVerified': 'Certified',
    'profile.certPending': 'Under Review',

    // 画师认证（三步骤）
    'verify.title': 'Artist Verification',
    'verify.subtitle': 'Submit your portfolio for manual review',
    'verify.step1.title': 'Select Your Style',
    'verify.step1.desc': 'Choose your creative styles (multiple selection allowed)',
    'verify.step1.handdrawn': 'Traditional',
    'verify.step1.digital': 'Digital',
    'verify.step2.title': 'Upload Artworks',
    'verify.step2.desc': 'Please upload at least 3 original artworks to showcase your style',
    'verify.step2.minHint': 'At least 3 artworks required',
    'verify.step3.title': 'Thank You for Becoming an Artist',
    'verify.step3.subtitle': 'This is certainly a brave decision',
    'verify.step3.desc': 'We have received your verification application. Please wait for our manual review. Once approved, your artworks will appear on the gallery and your profile 🐾',
    'verify.step3.backHome': 'Back to Home',
    'verify.next': 'Next',
    'verify.prev': 'Back',
    'verify.submit': 'Submit Application',
    'verify.uploadTitle': 'Upload Artworks',
    'verify.uploadDesc': 'Please upload at least 3 original artworks (max 9) to showcase your style',
    'verify.artworkType': 'Artwork Type',
    'verify.digital': 'Digital',
    'verify.handdrawn': 'Traditional',
    'verify.submitBtn': 'Submit for Review',
    'verify.pendingTitle': 'Under Review',
    'verify.pendingDesc': 'Your application is being reviewed. Please wait patiently 🐾',
    'verify.pendingBackHome': 'Back to Home',
    'verify.verifiedTitle': 'Certified',
    'verify.verifiedDesc': 'Congratulations! You are now a certified artist and can start taking commissions!',
    'verify.verifiedGoProfile': 'Go to My Profile',
    'verify.rejectedTitle': 'Not Approved',
    'verify.rejectedDesc': 'Your application was not approved. Please review the feedback and resubmit.',
    'verify.resubmit': 'Resubmit',
    'verify.selectAtLeastOne': 'Please select at least one style tag',
    'verify.uploadAtLeastThree': 'Please upload at least 3 artworks',
    'verify.submitSuccess': 'Application submitted. Please wait for admin review.',
    'verify.submitFailed': 'Submission failed',

    // 消息
    'messages.title': 'Messages',
    'messages.subtitle': 'Connect with your artists 🐾',
    'messages.escrow': 'Escrow Protected',
    'messages.noMessages': 'No messages yet',
    'messages.noMessagesDesc': 'Browse artists and start your first commission 🐾',
    'messages.findArtists': 'Find Artists',
    'messages.artist': 'Artist',
    'messages.client': 'Client',
    'messages.noAI': 'No AI',
    'messages.noAIDesc': '100% Human Reviewed',
    'messages.depositBadge': 'Deposit',
    'messages.depositBadgeDesc': 'Platform Escrow',
    'messages.fastReply': 'Fast Reply',
    'messages.fastReplyDesc': 'Artists Respond Quickly',
    'messages.aiWelcomePreview': 'Thank you for using PureDraw 🐾',
    'messages.aiSubtitle': 'Official Assistant',
    'messages.aiReadOnly': 'Official assistant is read-only. Contact support for help.',
    'messages.selectConversation': 'Select a conversation',
    'messages.selectConversationDesc': 'Choose a contact on the left to start chatting',
    'messages.activeCommission': 'Active Commission',
    'messages.acceptCommission': 'Accept',
    'messages.payDeposit': 'Pay Deposit',
    'messages.viewDetail': 'Details',
    'messages.sendFailed': 'Failed to send message',
    'messages.commissionSent': 'Commission request sent',
    'messages.commissionFailed': 'Failed to create commission',
    'messages.commissionAccepted': 'Commission accepted',
    'messages.priceMin': 'Minimum price is ¥70',

    // 聊天
    'chat.inputPlaceholder': 'Type a message...',
    'chat.send': 'Send',
    'chat.commission': 'Commission Details',

    // 约稿详情
    'commission.title': 'Commission Details',
    'commission.description': 'Description',
    'commission.price': 'Price',
    'commission.deposit': 'Deposit',
    'commission.status': 'Status',
    'commission.sketchDeadline': 'Sketch Deadline',
    'commission.finalDeadline': 'Final Deadline',
    'commission.uploadSketch': 'Upload Sketch',
    'commission.uploadFinal': 'Upload Final',
    'commission.confirmReceipt': 'Confirm Receipt',
    'commission.payDeposit': 'Pay Deposit',
    'commission.payFinal': 'Pay Balance',
    'commission.report': 'Request Takedown',
    'commission.statusMap.pending_agreement': 'Pending Agreement',
    'commission.statusMap.agreed': 'Agreed',
    'commission.statusMap.deposit_paid': 'Deposit Paid',
    'commission.statusMap.sketch_uploaded': 'Sketch Uploaded',
    'commission.statusMap.final_uploaded': 'Final Uploaded',
    'commission.statusMap.completed': 'Completed',
    'commission.statusMap.reported': 'Takedown Requested',
    'commission.statusMap.refunded': 'Refunded',
    'commission.statusMap.in_progress': 'In Progress',
    'commission.orderId': 'Order ID',
    'commission.notFound': 'Commission not found 🐾',
    'commission.backToMessages': 'Back to Messages',
    'commission.deliveryArea': 'Delivery Area',
    'commission.sketchSection': 'Sketch Phase',
    'commission.finalSection': 'Final Phase',
    'commission.noSketch': 'No sketch yet',
    'commission.noFinal': 'No final yet',
    'commission.confirmSketch': 'Approve Sketch',
    'commission.requestRevision': 'Request Revision',
    'commission.confirmAndPay': 'Confirm & Pay Balance',
    'commission.depositTitle': 'Agreement reached, please pay the deposit',
    'commission.depositDesc': 'The artist will start after deposit is paid. Funds are held in escrow for both parties 🐾',
    'commission.payDepositBtn': 'Pay Deposit ¥30',
    'commission.counterpart': 'Counterpart',
    'commission.sendMessage': 'Send Message',
    'commission.clientLabel': 'Client',
    'commission.artistLabel': 'Artist',
    'commission.afterSale': 'After-Sale Protection',
    'commission.afterSale1': 'You may cancel the commission before the sketch is delivered; no deposit refund.',
    'commission.afterSale2': 'If unsatisfied at sketch stage, request a redo or cancel and get ¥25 deposit refund.',
    'commission.afterSale3': 'If AI-generated content is found within 24 hours of receiving the final, submit a takedown request for an 80% refund.',
    'commission.terminateBtn': 'Cancel & Refund ¥25',
    'commission.reportAI': 'Request Takedown',
    'commission.reportPending': 'Takedown request feature coming soon. Contact support within 24h of receiving the final.',
    'commission.totalLabel': 'Total Price',
    'commission.deadlineLabel': 'Deadline',
    'commission.revisionTip': 'Please communicate revision requests with the artist via chat',
    'commission.payModal.deposit': 'Pay Deposit',
    'commission.payModal.balance': 'Pay Balance',
    'commission.payModal.scanTip': 'Scan with WeChat to pay',
    'commission.payModal.wechat': 'WeChat Pay Encrypted',
    'commission.payModal.testBtn': 'Simulate Payment (Test)',
    'commission.payModal.scanOpened': 'Payment QR ready, please scan 🐾',
    'commission.toast.depositPaid': 'Deposit paid! Commission is now active.',
    'commission.toast.finalPaid': 'Balance paid! Transaction complete.',
    'commission.toast.paymentMsg': '[System] Payment completed successfully.',
    'commission.toast.sketchUploaded': 'Sketch uploaded!',
    'commission.toast.finalUploaded': 'Final uploaded, awaiting client confirmation.',
    'commission.toast.uploadFailed': 'Upload failed',
    'commission.toast.sketchConfirmed': 'Sketch approved! Artist may now proceed with the final.',
    'commission.toast.refunded': '¥25 deposit refunded. Feel free to find your next artist 🐾',
    'commission.toast.sketchMsg': '[System] Sketch uploaded, please check the commission page.',
    'commission.toast.finalMsg': '[System] Final uploaded, please check the commission page.',
    'commission.toast.acceptMsg': '[System] I have accepted your commission, please pay the deposit.',
    'chat.sayHi': 'Say hi and start a pure creative exchange 🐾',
    'chat.systemMsgPrefix': '[System]',
    'chat.commissionRequest': 'New Commission Request',
    'chat.reqLabel': 'Description',
    'chat.reqPlaceholder': 'Describe your commission in detail: style, composition, purpose...',
    'chat.priceLabel': 'Price (min ¥70)',
    'chat.depositFixed': 'Deposit (fixed)',
    'chat.depositFixedValue': '¥30',
    'chat.sketchDeadline': 'Sketch Deadline',
    'chat.finalDeadline': 'Final Deadline',
    'chat.sendReq': 'Send Request',
    'chat.commSentMsg': 'Commission request sent. Description',
    'chat.statusNegotiating': 'Negotiating',
    'chat.statusAgreed': 'Awaiting Deposit',
    'chat.statusSketching': 'Sketching',
    'chat.statusSketchReview': 'Sketch Review',
    'chat.statusFinalizing': 'Finalizing',
    'chat.statusCompleted': 'Completed',
    'chat.statusDisputed': 'Takedown Under Review',
    'chat.statusRefunded': 'Refunded',
    'chat.artistRoleLabel': 'Certified Artist',
    'chat.clientRoleLabel': 'Client',
    'chat.currentComm': 'Active Commission',
    'chat.commProgress': 'Commission Progress',
    'chat.totalPrice': 'Total',
    'chat.depositLabel': 'Deposit',
    'chat.deadlineLabel': 'Deadline',
    'chat.acceptBtn': 'Accept & Start',
    'chat.payDepositBtn': 'Pay Deposit (¥30)',
    'chat.viewDetail': 'View Full Details',
    'chat.platformGuarantee': 'Commissions are fully protected by PureDraw 🐾',
    'chat.msgSendFailed': 'Failed to send message',
    'chat.priceTooLow': 'Minimum price is ¥70',
    'chat.reqSent': 'Commission request sent',
    'chat.reqFailed': 'Failed to create commission',
    'chat.accepted': 'Commission accepted',
    'chat.opFailed': 'Operation failed',
    'community.fillForm': 'Please fill in the title and content',
    'profile.admin': 'Admin',
    'profile.bioDefault': 'Every stroke carries warmth 🐾',
    'verify.artworkTitleBase': 'Artwork',
    'verify.selectedTags': 'Selected:',
    'verify.uploadedReady': 'uploaded — ready to submit',
    'notFound.title': 'Page Not Found',
    'notFound.error': 'Error',
    'notFound.desc': 'This page may have been deleted or does not exist. Please check the URL.',
    'notFound.backHome': 'Back to Home',
    'imageUpload.label': 'Upload Image',
    'imageUpload.unsupported': 'Unsupported file type. Please upload an image.',
    'imageUpload.compressing': 'File exceeds 1MB, compressing automatically...',
    'imageUpload.inProgress': 'Compressing image...',
    'imageUpload.compressed': 'Compressed, final size',
    'imageUpload.compressedToast': 'Image compressed to',
    'imageUpload.success': 'Image uploaded successfully!',
    'imageUpload.failed': 'Upload failed',
    'imageUpload.hint': 'Supports JPG, PNG, WEBP (max 1MB)',
    'imageUpload.uploading': 'Uploading...',
    'imageUpload.confirm': 'Confirm Upload',
    'admin.keywords.tab': 'Keyword Replies',
    'admin.keywords.title': 'Snail Cat Keyword Reply Manager',
    'admin.keywords.desc': 'Higher priority keywords are matched first. When multiple keywords match, the highest-priority reply is returned.',
    'admin.keywords.add': 'Add Keyword',
    'admin.keywords.empty': 'No keywords yet',
    'admin.keywords.emptyDesc': 'Click "Add Keyword" to create the first reply rule',
    'admin.keywords.editTitle': 'Edit Keyword Reply',
    'admin.keywords.addTitle': 'Add Keyword Reply',
    'admin.keywords.keywordLabel': 'Keyword (triggers when user message contains this)',
    'admin.keywords.keywordPlaceholder': 'e.g., certification, price, refund...',
    'admin.keywords.replyLabel': 'Auto-reply content',
    'admin.keywords.replyPlaceholder': 'Enter the Snail Cat reply message...',
    'admin.keywords.priorityLabel': 'Priority (higher number = matched first)',
    'admin.keywords.cancel': 'Cancel',
    'admin.keywords.save': 'Save',
    'admin.keywords.deleteTitle': 'Confirm Delete',
    'admin.keywords.deleteDesc': 'This keyword will no longer trigger auto-replies. Continue?',
    'admin.keywords.confirmDelete': 'Confirm Delete',
    'admin.keywords.updated': 'Keyword updated',
    'admin.keywords.added': 'Keyword added',
    'admin.keywords.saveFailed': 'Save failed',
    'admin.keywords.deleted': 'Deleted',
    'admin.keywords.deleteFailed': 'Delete failed',
    'admin.keywords.emptyCheck': 'Keyword and reply cannot be empty',
    'admin.keywords.showQuick': 'Show as Quick Question',
    'admin.keywords.showQuickTip': 'When enabled, this keyword appears as a quick question button in the assistant chat',
    'quickQ.title': 'Quick Questions',
    'quickQ.hint': 'Tap to ask',
    'home.featuredArtists': 'Featured Artists',
    'home.featuredDesc': 'Meet the artists who will inspire you',
    'home.noBio': 'This artist is a bit shy...',
    'home.noArtists': 'No artists yet. Be the first certified artist! 🐾',

    // 管理后台
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Maintaining a pure original art community 🐾',
    'admin.verifications': 'Verification Review',
    'admin.reports': 'Takedown Requests',
    'admin.users': 'User Management',
    'admin.approve': 'Approve',
    'admin.approveBtn': 'Approve',
    'admin.reject': 'Reject',
    'admin.rejectBtn': 'Reject',
    'admin.rejectReason': 'Rejection Reason',
    'admin.rejectPrompt': 'Enter rejection reason:',
    'admin.noVerifications': 'No pending applications 🐾',
    'admin.noReports': 'No pending takedown requests',
    'admin.noReportsDesc': 'Everything is clean — all cats are happily drawing 🐾',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.approveSuccess': 'Artist has been certified',
    'admin.rejectSuccess': 'Application rejected',
    'admin.actionFailed': 'Action failed',
    'admin.artistBio': 'Artist Bio',
    'admin.defaultBio': "This artist hasn't written a bio yet...",
    'admin.styleDigital': 'Digital',
    'admin.styleHanddrawn': 'Traditional',
    'admin.verificationTab': 'Verification Review',
    'admin.reportTab': 'Takedown',

    // 社区
    'community.original': 'Original',
    'community.titlePlaceholder': 'Title (give your idea a name)',
    'community.maxImages': 'max 4',
    'community.uploadImage': 'Upload Image',
    'community.likedMsg': 'Liked 🐾',
    'community.commentSoon': 'Coming soon',
    'community.shareSuccess': 'Shared!',
    'community.publishSuccess': 'Published!',
    'community.publishFailed': 'Publish failed: ',
    'community.loginToPost': 'Please log in to post',
  },
} as const;

type TranslationKey = keyof typeof translations.zh;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('puredraw-language');
    return (saved === 'en' || saved === 'zh') ? saved : 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('puredraw-language', lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] ?? translations.zh[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
